# Generated by Django 3.0.6 on 2020-05-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongsCleared',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('song', models.TextField()),
                ('chatid', models.IntegerField()),
                ('level', models.IntegerField()),
            ],
            options={
                'db_table': 'SongsCleared',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('chatid', models.IntegerField(primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
