# Generated by Django 3.0.6 on 2020-05-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.TextField()),
                ('cut', models.TextField()),
                ('image', models.TextField()),
            ],
            options={
                'db_table': 'TitleCard',
                'unique_together': {('song', 'cut')},
            },
        ),
    ]
